[project]
name = "learning"
version = "0.1.0"
description = "Django проект для управления курсами и уроками"
authors = [
    {name = "Your Name", email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.3,<7.0.0",
    "djangorestframework>=3.17.0,<4.0.0",
    "django-filter>=25.2,<26.0",
    "djangorestframework-simplejwt>=5.5.1,<6.0.0",
    "psycopg2-binary>=2.9.11,<3.0.0",
    "python-dotenv>=1.2.2,<2.0.0",
    "pillow>=12.1.1,<13.0.0",
    "PyJWT>=2.12.1,<3.0.0",
    "drf-yasg (>=1.21.15,<2.0.0)",
    "stripe (>=15.0.1,<16.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"